displayName=Auto Minimap Zoom % and Hotkey
author=Razza98
description=Hotkey that sets a Minimap Zoom percentage and Automatically applies it after loading areas or changing worlds
tags=minimap,zoom,hotkey,utility,auto
version=1.0.0
plugins=minimapzoom.MinimapZoomPlugin
build=standard
