displayName=Minimap Zoom
author=RYANOATES
description=Automatically apply your minimap zoom after loading areas or changing worlds.
tags=minimap,zoom,hotkey,utility
version=1.0.0
plugins=minimapzoom.MinimapZoomPlugin
build=standard
